### ISSUE TITLE
Uninitialized constant Warden::Strategies::Doorkeeper::OAuth

### ISSUE THREAD

**Issue by edmondchui** [kolorahl/warden-doorkeeper#1]
I hit the exception uninitialized constant Warden::Strategies::Doorkeeper::OAuth in this line: 

https://github.com/kolorahl/warden-doorkeeper/blob/master/lib/warden/strategies/doorkeeper.rb#L15

``` ruby
 @token = OAuth::Token.authenticate(request, *Doorkeeper.configuration.access_token_methods)
```

To fix it, we need to add a global scope for it:

``` ruby
 @token = ::Doorkeeper::OAuth::Token.authenticate(request, *Doorkeeper.configuration.access_token_methods)
```

**Comment by tyler-eon** [comment]
Sorry I didn't get around to this a bit earlier, I was out of town for a few days. Thanks for the PR though, good catch!

**Comment by edmondchui** [comment]
Thanks!

**Comment by edmondchui** [comment]
Could you please increase the version number so that we can get update?

**Comment by tyler-eon** [comment]
Done, and pushed to rubygems.org.

**Comment by edmondchui** [comment]
Cool. Thanks. I got version 0.3.0 now.
